# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x1a\x61uthentication.grpc_config\"\x1c\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\".\n\x0c\x41uthResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t2p\n\x0b\x41uthService\x12\x61\n\x0c\x41uthenticate\x12\'.authentication.grpc_config.AuthRequest\x1a(.authentication.grpc_config.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=42
  _globals['_AUTHREQUEST']._serialized_end=70
  _globals['_AUTHRESPONSE']._serialized_start=72
  _globals['_AUTHRESPONSE']._serialized_end=118
  _globals['_AUTHSERVICE']._serialized_start=120
  _globals['_AUTHSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
