# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/auth.proto\x12\x1a\x61uthentication.grpc_config\"\x1c\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\"?\n\x0c\x41uthResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2p\n\x0b\x41uthService\x12\x61\n\x0c\x41uthenticate\x12\'.authentication.grpc_config.AuthRequest\x1a(.authentication.grpc_config.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=48
  _globals['_AUTHREQUEST']._serialized_end=76
  _globals['_AUTHRESPONSE']._serialized_start=78
  _globals['_AUTHRESPONSE']._serialized_end=141
  _globals['_AUTHSERVICE']._serialized_start=143
  _globals['_AUTHSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
